name: Add PR to project
on:
  pull_request:
    types:
      - ready_for_review
jobs:
  track_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.ET_GHP_TEST_WORKFLOW_APP1_ID }}
          private_key: ${{ secrets.ET_GHP_TEST_WORKFLOW_APP1_PRIVATE_KEY }}
